### ISSUE TITLE
Fixed enderpearl penetration

### ISSUE THREAD

**Issue by BakuQ** [CobbleSword/NachoSpigot#329]
### Describe the feature

I propose to add the possibility of setting the enderpearl penetration through half-blocks, threads, stairs, hurdles

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

**Comment by sadcenter** [comment]
I think there are options in Paper that allow a player to ender pearl through blocks
```yml
pearl-passthrough:
  fence_gate: false
  bed: false
  slab: false
  cobweb: false
  tripwire: false
  ```
